# -*- coding: utf-8 -*-
"""CV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4pgrFG8TWJPhK4Ss5_dNShL671-Zm0N
"""

import numpy as np

black_img= np.zeros((100,100,3),dtype=np.uint8)

black_img

import cv2
import numpy
import os

# Make an array of 120,000 random bytes.
randomByteArray = bytearray(os.urandom(120000))
flatNumpyArray = numpy.array(randomByteArray)

# Convert the array to make a 400x300 grayscale image.
grayImage = flatNumpyArray.reshape(300, 400)
cv2.imwrite('RandomGray.png', grayImage)

# Convert the array to make a 400x100 color image.
bgrImage = flatNumpyArray.reshape(100, 400, 3)
cv2.imwrite('RandomColor.png', bgrImage)

import cv2 as cv
img=cv.imread("lenna.png")
img.shape

img[0,0]

#accessing only blue pixel
blue = img[100,100,0]
print( blue )

img[100,100] = [255,255,255]
print( img[100,100] )

# splitting and merging Image Channel

b,g,r = cv.split(img)
b,g,r

img = cv.merge((b,g,r))

img

#image Addition
cv2.imwrite('grayy_image.png',img)

img1=cv2.imread('lenna.png')
img2=cv2.imread('lenna.png')
img1=cv2.resize(img1,(512,512))
img2=cv2.resize(img2,(512,512))
new=cv2.addWeighted(img1,.5,img2,.5,0)

new

import cv2
from google.colab.patches import cv2_imshow
image = cv2.imread("lenna.png")
# Select ROI
r = cv2.selectROI("select the area", image)
# Crop image
cropped_image = image[int(r[1]):int(r[1]+r[3]),
int(r[0]):int(r[0]+r[2])]
# Display cropped image
cv2_imshow("Cropped image", cropped_image)

